name: "Graph build times to wiki page"
description: "Genertates and pushes graph of build times to a GitHub project's wiki"

inputs:
  github-personal-token:
    description: 'Github personal access token used to push graph to remote'
    required: true
  github-token:
    description: 'Github token used for Github API requests'
    required: true
    default: ${{ github.token }}
  workflow-name:
    description: |
      'Name of the worflow (yaml file or Github's unique workflow ID number)
      for which the graph will be generated'
    remote: true



runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "book-open"
  color: "white"
