name: "Graph build times to wiki page"
description: "Genertates and pushes graph of build times to a GitHub project's wiki"

inputs:
  github_personal_token:
    description: 'Github personal access token used to push graph to remote'
    required: true
  github_token:
    description: 'Github token used for Github API requests'
    required: true
    default: ${{ github.token }}
  workflow:
    description: |
      'Name of the worflow (yaml file or Github's unique workflow ID number)
      for which the graph will be generated'
    remote: true
  filename:
    description: 'Filename for the generated graph that will be pushed to the wiki repo'
    required: true
    default: 'graph.png'

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "book-open"
  color: "white"
