name: "Graph build times to wiki page"
description: "Genertates and pushes graph of build times to a GitHub project's wiki"

inputs:
  github_personal_token:
    description: 'Github personal access token used to push graph to remote wiki repo'
    required: true
  github_token:
    description: 'Github token used for Github API requests'
    required: true
    default: ${{ github.token }}
  workflow:
    description: |
      'Name of the worflow (yaml file or Github's unique workflow ID number)
      for which the graph will be generated'
    required: true
  filename:
    description: 'Filename for the generated graph that will be pushed to the wiki repo'
    required: true
    default: 'graph.png'
  repo:
    description: |
      'Repository name where queried workflow is being run. If not provided, the value of GITHUB_REPOSITORY will be used,
      which is the name of the repository on which this action is run'
    default: ${{ github.repository }}
  num_last_build:
    description: 'Number of last builds to be used for generating graph'
    default: '10'
  branch:
    description: 'Branch name for which build times should be plotted'
  title:
    description: 'Title of the generated graph'
  x_label:
    description: 'X axis label'
    default: Run number
  y_label:
    description: 'Y axis label'
    default: Build time (min)
  graph_width:
    description: 'Graph width in inches'
    default: 6.4
  graph_height:
    description: 'Graph height in inches'
    default: 4.8
  build_file:
    description: 'file with build time'
  commit_message:
    description: 'Commit message for wiki page'
  docker_username:
    description: 'Username to dockerhub'
    required: true
  docker_password:
    description: 'Password to dockerhub'
    required: true
  docker_repository:
    description: 'Docker image name'
    required: true
  run_id:
    description: 'Current workflow run ID'
    required: true
    default: ${{github.run_number}}


runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "book-open"
  color: "white"
