name: 'Get time of action'
description: 'How much time did last run take'
inputs:
  owner:
    required: true
  repo:
    required: true
  run_id:
    required: true
outputs:
  time: # id of output
    description: 'Time it took for given action'
runs:
  using: 'node12'
  main: 'index.js'