name: "Graph build times to wiki page"
description: |
 "GitHub action that generates a graph of build times and pushes it to project's wiki page"

inputs:
  github_personal_token:
    description: 'Github personal access token used to push graph to remote wiki repo'
    required: true
  build_stats_output:
    description: 'Wiki repo directory for generated build data. Defaults to root directory'
  build_times_filename:
    description: 'Filename where the previous build times are stored. File format should be CSV'
    default: 'build_times.csv'
  build_result_filename:
    description: 'Path to ClangBuildAnalyzer file (txt format)'
    default: 'build_result.txt'
  graph_filename:
    description: 'Filename for the generated graph that will be pushed to the wiki repo'
    default: 'graph.png'
  badge_filename:
    description: 'Filename for generated badge which displays most recent build time.File format should be SVG'
    default: 'build_status_badge.svg'
  badge_title:
    description: 'Name that will be displayed on the badge'
    default: ${{ github.repository }} build time
  badge_logo:
    description: 'Logo which will be displayed on the badge. For the list of logos see https://shields.io/'
  num_last_build:
    description: 'Number of last builds used for generating graph'
    default: '25'
  title:
    description: 'Title of the generated graph'
  x_label:
    description: 'X axis label'
    default: Run number
  y_label:
    description: 'Y axis label'
    default: Build time (min)
  graph_width:
    description: 'Graph width in inches'
    default: 19
  graph_height:
    description: 'Graph height in inches'
    default: 15
  commit_message:
    description: 'Commit message for wiki page'
    default: Push build time graph

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "book-open"
  color: "white"
