name: Test

on: push

jobs:
    test_job:
      runs-on: ubuntu-latest
      name: Test job
      steps:
      - name: Generate wiki page
        uses: DARMA-tasking/graph-build-times@7-add-static-analysis
        with:
          github_personal_token: ${{ secrets.GPAT }}
          title: Last builds
          graph_width: 20
          graph_height: 20
          build_stats_output: "build_stats"




