name: Test
on:
  workflow_run:
    workflows: ["Dispatcher"]
    types:
      - completed

jobs:
    test_job:
      runs-on: ubuntu-latest
      name: Test job
      steps:
      - name: Get the file
        uses: actions/upload-artifact@v2
        with:
          name: homework
      - shell: bash
        run: cat math-homework.txt
      - name: Ubuntu full build
        uses: JacobDomagala/TestAction@master
        with:
          github_personal_token: ${{ secrets.GPAT }}
          github_token: ${{ github.token }}
          workflow: lint.yml
          filename: build_times_ubuntu.png
          build_file: math-homework.txt
          repo: pytorch/pytorch
          num_last_build: 50
          title: Last 50 builds
          graph_width: 19
          graph_height: 8
          branch: master



