name: Test_Action

on: [pull_request]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test job
    steps:
    - name: Test Action
      uses: DARMA-tasking/graph-build-times@1-create-the-github-action
      with:
        github_personal_token: ${{ secrets.GPAT }}
        github_token: ${{ github.token }}
        workflow: test.yml
        filename: build_times.png
        num_last_build: 50
        title: Last 50 builds
        graph_width: 19
        graph_height: 8
        branch: graph-build-time
