name: Test_Action

on: [pull_request]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test job
    steps:
    - name: Test Action
      uses: JacobDomagala/TestAction@graph-build-time
      with:
        github_personal_token: ${{ secrets.GPAT }}
        github_token: ${{ github.token }}
        workflow: pushdockerimage.yml
        filename: build_times.png
        repo: DARMA-tasking/vt
        num_last_build: 50
        title: Last 50 builds
        graph_width: 19
        graph_height: 8
        branch: develop
